# Generated by Django 3.0.8 on 2021-01-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201231_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Email',
        ),
    ]
