# Generated by Django 3.0.8 on 2021-01-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_orders_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
